import type { ComponentRegistry } from "framework/components/componentRegistry";
import { Transform } from "framework/components/transform";
import { Size } from "framework/components/size";
import { Velocity, Acceleration, Collider, ColliderShape } from "framework/components/physics";
import { Health, Attack, Defense, Team } from "framework/components/combat";
import { AIState, Target, BlackboardRef } from "framework/components/ai";
import { Inventory, initInventory } from "framework/components/inventory";
import { ItemMeta } from "framework/components/itemMeta";
import { Needs, initNeeds } from "framework/components/needs";
import { ResourceNode, initResourceNode } from "framework/components/resourceNode";
import { LootTable, initLootTable } from "framework/components/loot";
import { Perception } from "framework/components/perception";
import { Equipment } from "framework/components/equipment";
import { CraftingStation } from "framework/components/craftingStation";
import { LightSource } from "framework/components/lightSource";
import { Placeable } from "framework/components/placeable";
import { GridOccupancy } from "framework/components/gridOccupancy";
import { Portal, initPortal } from "framework/components/portal";
import { Intent } from "framework/components/intent";
import { NetworkId, LastSynced } from "framework/components/network";
import { Cooldown, Duration } from "framework/components/timer";
import { Player, Enemy, NPC, Item, Resource } from "framework/components/tags";
import { Kind } from "framework/components/kind";

export function registerBuiltinComponents(registry: ComponentRegistry): void {
  registry.register("Transform", Transform);
  registry.register("Size", Size);
  registry.register("Velocity", Velocity);
  registry.register("Acceleration", Acceleration);
  registry.register("Collider", Collider);
  registry.register("Health", Health);
  registry.register("Attack", Attack);
  registry.register("Defense", Defense);
  registry.register("Team", Team);
  registry.register("AIState", AIState);
  registry.register("Target", Target);
  registry.register("BlackboardRef", BlackboardRef);
  registry.register("Inventory", Inventory);
  registry.register("ItemMeta", ItemMeta);
  registry.register("Needs", Needs);
  registry.register("ResourceNode", ResourceNode);
  registry.register("LootTable", LootTable);
  registry.register("Perception", Perception);
  registry.register("Equipment", Equipment);
  registry.register("CraftingStation", CraftingStation);
  registry.register("LightSource", LightSource);
  registry.register("Placeable", Placeable);
  registry.register("GridOccupancy", GridOccupancy);
  registry.register("Portal", Portal);
  registry.register("Intent", Intent);
  registry.register("NetworkId", NetworkId);
  registry.register("LastSynced", LastSynced);
  registry.register("Cooldown", Cooldown);
  registry.register("Duration", Duration);
  registry.register("Player", Player);
  registry.register("Enemy", Enemy);
  registry.register("NPC", NPC);
  registry.register("Item", Item);
  registry.register("Resource", Resource);
  registry.register("Kind", Kind);

  // AoS 组件初始化钩子
  registry.registerAosInitializer("Inventory", initInventory);
  registry.registerAosInitializer("Needs", initNeeds);
  registry.registerAosInitializer("ResourceNode", initResourceNode);
  registry.registerAosInitializer("LootTable", initLootTable);
  registry.registerAosInitializer("Portal", initPortal);
}
